"""English variants of the teaching error popups (mirrors ERROR_EXPLANATIONS)."""

ERROR_EXPLANATIONS_EN: dict[str, tuple[str, tuple[str, ...]]] = {
    "PORT_INVALID": ("Invalid port", ("Ports must be 1-65535 and not collide with another instance", "How: pick the next free port (default is 18010 + worker number)")),
    "INSTANCE_NOT_FOUND": ("Connector not found", ("Missing: it may have been deleted or moved", "How: press Rescan and pick from the fresh list")),
    "INSTANCE_OUTSIDE_ROOT": ("Connector is outside the managed root", ("The instance folder must live under C:\\AI\\serena-instances", "How: move it back under the root before acting on it")),
    "INSTANCE_NAME_INVALID": ("Invalid connector name", ("Names must be lowercase English letters/digits/hyphens", "How: check the name you typed and retry")),
    "INSTANCE_DISPLAY_NAME_INVALID": ("Display name cannot be blank", ("Missing: text in the name field", "How: type at least one character and save again")),
    "REFERENCE_PS1_INVALID": ("Reference instance.ps1 is invalid", ("Missing: the $TunnelClientPath / $LegacySecretPath lines in the reference", "How: pick a different reference or repair its instance.ps1 first")),
    "REFERENCE_SCRIPT_MISSING": ("Reference scripts incomplete", ("Missing: start.ps1 or stop.ps1 in the reference folder", "How: use a complete connector as the reference")),
    "REFERENCE_CMD_MISSING": ("Reference cmd wrappers incomplete", ("Missing: Start-*.cmd or Stop-*.cmd in the reference folder", "How: use a complete connector as the reference")),
    "REFERENCE_TEMPLATE_MISSING": ("Reference profile template incomplete", ("Missing: profiles/*.yaml.template or serena_config.yml", "How: use a complete connector as the reference")),
    "CREATE_VERIFY_FAILED": ("Created but not discovered afterwards", ("The post-create discovery did not find the new instance", "How: press Rescan, or recreate with another name")),
    "INSTANCE_CREATE_FAILED": ("Connector creation failed", ("What: a filesystem-level failure (disk/permissions)", "How: check the ACTIVITY / LOG panel and retry")),
    "INSTANCE_RENAME_FAILED": ("Rename failed", ("What: writing to the database failed", "How: retry, or restart the app and try again")),
    "PROVIDER_STORE_NOT_AVAILABLE": ("Provider controls unavailable", ("What: the retained provider store is unavailable", "How: reopen Settings or restart the app; no provider change was made")),
    "PROVIDER_GENERATION_STALE": ("Provider changed before save", ("What: this view is older than the stored provider generation", "How: Refresh and review the latest values before trying again")),
    "PROVIDER_GENERATION_EXPECTED": ("Provider generation required", ("What: a safe provider update requires the generation that was read", "How: Refresh the provider row and retry once")),
    "PROVIDER_GENERATION_EXHAUSTED": ("Provider generation exhausted", ("What: this provider can no longer advance its generation counter", "How: stop editing and preserve the database for review")),
    "PROVIDER_CONFIGURATION_IN_USE": ("Provider is in use", ("Blocked: an active or unreconciled admission still owns this provider", "How: let running work finish/reconcile, then Refresh and retry")),
    "PROVIDER_PROFILE_INVALID": ("Provider edit is invalid", ("What: one or more editable fields failed validation", "How: correct the fields; secret or endpoint values are never shown here")),
    "PROVIDER_TEST_TARGET_UNAVAILABLE": ("Provider test target unavailable", ("What: the provider, endpoint, or generation vanished before Test began", "How: Refresh and select the provider again")),
    "PROVIDER_OBSERVATION_GENERATION_STALE": ("Test result became stale", ("What: provider configuration changed while Test was running", "How: Refresh and run Test again only if the new configuration still needs evidence")),
    "PROVIDER_CONFIGURATION_CORRUPT": ("Provider configuration is corrupt", ("What: persisted provider data failed typed decoding", "How: do not edit from this panel; repair the stored configuration through the accepted recovery path")),
    "CONFIG_STORE_UNAVAILABLE": ("Provider database unavailable", ("What: the provider control database could not be opened", "How: verify the control database path and permissions, then Refresh")),
    "CONFIG_STORE_SCHEMA_UNAVAILABLE": ("Provider schema unavailable", ("What: the control database does not contain the required provider schema", "How: reopen the current app version against the correct control database")),
    "CONFIG_STORE_READ_FAILED": ("Provider database read failed", ("What: SQLite could not read the provider configuration", "How: retry Refresh; if it repeats, inspect the control database and logs")),
    "PROVIDER_ACTION_FAILED": ("Provider action failed", ("What: the provider action returned an unexpected typed boundary failure", "How: Refresh and check ACTIVITY / LOG before retrying")),
    "GENERIC": ("Something went wrong", ("What: an unexpected error occurred", "Try: press Refresh; if it repeats, check the log panel")),
    "SELECT_WORKER": ("No Worker selected", ("Missing: a click on a row in the WORKERS table (right side)", "How: click a Worker row once, then press the button")),
    "SELECT_PROJECT": ("No project selected", ("Missing: a selection in the PROJECTS list (left side)", "How: pick a project, then a target Worker, then press Assign")),
    "SELECT_INSTANCE": ("No connector selected", ("Missing: a click on a row in the CONNECTORS table", "How: click a connector row once, then press the button")),
    "WORKER_NAME_INVALID": ("Worker name cannot be blank", ("Missing: text in the name field", "How: type at least one character, then press Save")),
    "ASSIGNMENT_CONFLICT": ("Assignment conflict", ("Blocked: the new project/worktree conflicts with another mutating assignment or runtime", "How: choose a non-conflicting Worker/project or stop the existing work, then Assign again")),
    "REGISTRY_NOT_FOUND": ("Worker or Project not found", ("Missing: the selected item is no longer present in the latest registry state", "How: Refresh, select the Project and Worker again, then retry")),
    "WORKER_BUSY": ("Worker is busy", ("Blocked: the Worker must be STOPPED before changing projects", "How: Stop it, then Assign the new project again; A-Conductor will ask before replacing the current assignment")),
    "INSTANCE_CREATE_NOT_AVAILABLE": ("Connector creation unavailable", ("Missing: the creation service in this build", "How: update the app to the latest version and retry")),
    "INSTANCE_FIELDS_REQUIRED": ("Incomplete form", ("Missing: connector name or project path", "How: fill both fields (one English word + a full folder path)")),
    "NAME_INVALID": ("Invalid connector name", ("Names must be lowercase English letters/digits/hyphens, e.g. research", "How: no spaces or symbols — one word like research or chat-beta")),
    "NAME_ALREADY_EXISTS": ("Name already used", ("Missing: a name not already taken by another connector", "How: choose another name, or press Rescan to see current names")),
    "PROJECT_NOT_FOUND": ("Project folder not found", ("Missing: a project path that exists on this machine", "How: check the full path, e.g. A:\\GitHub\\my-project (a real folder)")),
    "TUNNEL_ID_INVALID": ("Invalid Tunnel ID format", ("IDs start with tunnel_ followed by 32 hex characters", "How: copy it fresh from the OpenAI Platform, or leave blank and set later")),
    "REFERENCE_MISSING": ("No reference connector found", ("Missing: at least one validated connector in C:\\AI\\serena-instances", "How: create the first connector per the guide, then use this button")),
    "INSTANCE_STOP_REQUIRED": ("Connector must be stopped first", ("Blocked: the connector is still running", "How: press Stop, wait for STOPPED, then retry; or check that connector's log")),
    "INSTANCE_BACKUP_FAILED": ("Backup before delete failed", ("Missing: the zip backup was not created (disk full or path not writable)", "How: check disk space and the instance-backups folder — nothing was deleted")),
    "INSTANCE_DELETE_FAILED": ("Could not remove the connector folder", ("Blocked: a file is locked by another program", "How: close windows/programs using that folder and retry (the zip backup is kept)")),
    "INSTANCE_RENAME_NOT_AVAILABLE": ("Connector rename unavailable", ("Missing: the rename service in this build", "How: update the app to the latest version and retry")),
    "INSTANCE_DELETE_NOT_AVAILABLE": ("Connector delete unavailable", ("Missing: the delete service in this build", "How: update the app to the latest version and retry")),
    "INSTANCE_REFRESH_FAILED": ("Could not refresh connectors", ("What: the instances list could not be loaded", "How: press Rescan; if it repeats, check that C:\\AI\\serena-instances exists")),
    "INSTANCE_ACTION_FAILED": ("Connector action failed", ("What: the start/stop script returned an error", "How: open that connector's log under its logs\\ folder for the reason")),
    "INSTANCE_START_ALL_FAILED": ("Start All failed", ("What: one or more connectors failed to start", "How: check each connector's state and its logs\\ folder")),
    "INSTANCE_FLAG_FAILED": ("Could not save the auto-start flag", ("What: writing the flag to the database failed", "How: retry the toggle; if it repeats, restart the app")),
    "INSTANCES_NOT_AVAILABLE": ("Connectors unavailable", ("Missing: the connector service in this build", "How: update the app to the latest version and retry")),
    "CONNECTOR_MATCH_MISSING": ("Connector lookup failed", ("What: the expected connector could not be matched", "How: press Rescan and check the CONNECTORS table")),
    "REBIND_NOT_AVAILABLE": ("Project rebind unavailable", ("Missing: the rebind service in this build", "How: update the app to the latest version and retry")),
    "REBIND_FAILED": ("Project rebind failed", ("What: rewriting the connector files failed", "How: check the message details; .bak backups were kept beside each file")),
    "TUNNEL_SETUP_NOT_AVAILABLE": ("Tunnel ID setup unavailable", ("Missing: the tunnel-id writer in this build", "How: update the app to the latest version and retry")),
    "UPSTREAM_CHECK_FAILED": ("Upstream check failed", ("What: the GitHub request failed or timed out", "How: check your internet connection and retry later")),
    "PREFERENCES_NOT_AVAILABLE": ("Preferences unavailable", ("Missing: the preferences store in this build", "How: update the app to the latest version and retry")),
    "PREFERENCES_LOAD_FAILED": ("Could not load preferences", ("What: reading the settings database failed", "How: restart the app; defaults apply meanwhile")),
    "PREFERENCE_SAVE_FAILED": ("Could not save the preference", ("What: writing the setting to the database failed", "How: toggle again; if it repeats, restart the app")),
    "LIFECYCLE_NOT_WIRED": ("Lifecycle control not available", ("Missing: a lifecycle service in this build", "How: update the app to the latest version and retry")),
    "LIFECYCLE_COMMAND_FAILED": ("Lifecycle command failed", ("What: Start/Stop/Restart returned an error", "How: check the log panel for the step that failed")),
    "LIFECYCLE_RESULT_INVALID": ("Lifecycle returned an invalid result", ("What: the result could not be understood", "How: press Refresh and check the Worker state")),
    "RUNTIME_SETUP_NOT_AVAILABLE": ("Runtime setup unavailable", ("Missing: the setup service in this build", "How: update the app to the latest version and retry")),
    "RUNTIME_SETUP_FAILED": ("Runtime setup failed", ("What: preparing the Worker runtime failed", "How: check the message details; ports may be in use")),
    "RUNTIME_SETUP_RESULT_INVALID": ("Setup returned an invalid result", ("What: the setup result could not be understood", "How: reopen the Setup dialog and retry")),
    "RUNTIME_SETUP_SAVE_FAILED": ("Could not save the runtime setup", ("What: writing the setup files failed", "How: check disk space and folder permissions")),
    "HEALTH_PORT_INVALID": ("Invalid health port", ("Ports must be 1-65535 and not collide with existing workers", "How: pick the next free port (default is 18010 + worker number)")),
    "SETTINGS_NOT_AVAILABLE": ("Engine settings unavailable", ("Missing: the settings service in this build", "How: update the app to the latest version and retry")),
    "SETTINGS_LOAD_FAILED": ("Could not load engine settings", ("What: reading the settings database failed", "How: reopen the Config dialog; defaults apply meanwhile")),
    "SETTINGS_SAVE_FAILED": ("Could not save engine settings", ("What: writing the settings failed", "How: retry Save; if it repeats, restart the app")),
    "SETTINGS_INVALID": ("Invalid engine settings", ("What: one or more values were rejected", "How: fix the highlighted fields and save again")),
    "SETTINGS_RESULT_INVALID": ("Settings returned an invalid result", ("What: the save result could not be understood", "How: reopen the Config dialog and retry")),
    "SETTINGS_LANGUAGE_BACKEND_INVALID": ("Invalid language backend", ("Backend must be LSP or JetBrains", "How: choose one of the two options")),
    "SETTINGS_TOOL_TIMEOUT_INVALID": ("Invalid tool timeout", ("Timeout must be 1-86400 seconds", "How: enter a number in that range")),
    "PROJECT_IDENTITY_SAVE_FAILED": ("Could not save the project identity", ("What: writing the identity file failed", "How: check disk space and folder permissions")),
    "GUIDE_NOT_FOUND": ("User guide file not found", ("Missing: docs/USER-GUIDE.md next to the app", "How: reinstall or clone the full repository")),
    "GUIDE_OPEN_FAILED": ("Could not open the guide", ("What: opening the guide window failed", "How: retry; if it repeats, open docs/USER-GUIDE.md directly")),
    "CLIPBOARD_COPY_FAILED": ("Copy failed", ("What: writing to the clipboard failed", "How: retry, or select the text manually")),
    "CONTROL_CENTER_START_FAILED": ("App startup failed", ("What: the control database could not be opened", "How: check that the --database path is writable")),
}
