"""Strict concrete read-only Windows I/O backends.

The PowerShell backend is intentionally not a generic shell runner: it accepts
only the exact bounded process/port inspection scripts generated by
``WindowsRuntimeObserver``. The HTTP backend accepts only loopback ``/readyz``
GET requests. Neither backend owns target lifecycle mutation.
"""

from __future__ import annotations

import ipaddress
import re
import subprocess
from pathlib import PureWindowsPath
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import Request, urlopen

from .windows_observer import (
    CommandResult,
    HealthProbeObservation,
    HealthProbeState,
)


_PROCESS_INSPECTION_RE = re.compile(
    r'\$p = Get-CimInstance Win32_Process -Filter "ProcessId=[1-9][0-9]*" '
    r'-ErrorAction SilentlyContinue; '
    r'if \(\$null -eq \$p\) \{ exit 0 \}; '
    r'\$p \| Select-Object ProcessId,Name,ExecutablePath,CommandLine '
    r'\| ConvertTo-Json -Compress'
)

_PORT_INSPECTION_RE = re.compile(
    r'\$c = Get-NetTCPConnection -State Listen -LocalPort [1-9][0-9]* '
    r'-ErrorAction SilentlyContinue \| Select-Object -First 1; '
    r'if \(\$null -eq \$c\) \{ exit 0 \}; '
    r'\$c \| Select-Object LocalAddress,LocalPort,OwningProcess '
    r'\| ConvertTo-Json -Compress'
)

_UTF8_OUTPUT_PREFIX = (
    '[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false); '
)


def _require_timeout(timeout_seconds: int) -> int:
    if (
        not isinstance(timeout_seconds, int)
        or isinstance(timeout_seconds, bool)
        or timeout_seconds < 1
    ):
        raise ValueError("timeout_seconds must be >= 1")
    return timeout_seconds


def _is_allowlisted_inspection_script(script: str) -> bool:
    return (
        _PROCESS_INSPECTION_RE.fullmatch(script) is not None
        or _PORT_INSPECTION_RE.fullmatch(script) is not None
    )


def _is_loopback_host(hostname: str) -> bool:
    if hostname.casefold() == "localhost":
        return True
    try:
        return ipaddress.ip_address(hostname).is_loopback
    except ValueError:
        return False


class StrictPowerShellInspectionRunner:
    """Run only the two allowlisted inspection command shapes."""

    def __init__(self, powershell_executable: str = "powershell.exe") -> None:
        if not isinstance(powershell_executable, str) or not powershell_executable.strip():
            raise ValueError("powershell_executable must not be blank")
        self._powershell_executable = powershell_executable.strip()

    def run(self, argv: tuple[str, ...], timeout_seconds: int) -> CommandResult:
        timeout = _require_timeout(timeout_seconds)
        if len(argv) != 5:
            raise ValueError("PowerShell invocation is not allowlisted")

        executable, no_profile, non_interactive, command_flag, script = argv
        expected_name = PureWindowsPath(self._powershell_executable).name.casefold()
        observed_name = PureWindowsPath(executable).name.casefold()
        if (
            observed_name != expected_name
            or no_profile != "-NoProfile"
            or non_interactive != "-NonInteractive"
            or command_flag != "-Command"
        ):
            raise ValueError("PowerShell invocation is not allowlisted")

        if not _is_allowlisted_inspection_script(script):
            raise ValueError("inspection command is not allowlisted")

        actual_argv = (
            self._powershell_executable,
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            _UTF8_OUTPUT_PREFIX + script,
        )
        try:
            completed = subprocess.run(
                list(actual_argv),
                shell=False,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
                check=False,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
        except subprocess.TimeoutExpired:
            return CommandResult(return_code=124, stdout="", stderr="TIMEOUT")
        except OSError:
            return CommandResult(
                return_code=127,
                stdout="",
                stderr="EXECUTION_ERROR",
            )

        return CommandResult(
            return_code=int(completed.returncode),
            stdout=completed.stdout or "",
            stderr=completed.stderr or "",
        )


class LoopbackReadyzHttpProbe:
    """Perform a bounded GET only against an allowlisted loopback readyz URL."""

    def get(self, url: str, timeout_seconds: int) -> HealthProbeObservation:
        timeout = _require_timeout(timeout_seconds)
        self._validate_url(url)
        request = Request(url, headers={"Accept": "text/plain"}, method="GET")

        try:
            with urlopen(request, timeout=timeout) as response:
                status = getattr(response, "status", None)
        except HTTPError as exc:
            code = int(exc.code)
            return HealthProbeObservation(
                state=HealthProbeState.NOT_READY,
                status_code=code,
                error_code=f"HTTP_{code}",
            )
        except (URLError, TimeoutError, OSError):
            return HealthProbeObservation(
                state=HealthProbeState.NOT_READY,
                status_code=None,
                error_code="TRANSPORT_ERROR",
            )

        if status == 200:
            return HealthProbeObservation(
                state=HealthProbeState.READY,
                status_code=200,
                error_code=None,
            )
        if isinstance(status, int):
            return HealthProbeObservation(
                state=HealthProbeState.NOT_READY,
                status_code=status,
                error_code=f"HTTP_{status}",
            )
        return HealthProbeObservation(
            state=HealthProbeState.UNKNOWN,
            status_code=None,
            error_code="STATUS_UNKNOWN",
        )

    @staticmethod
    def _validate_url(url: str) -> None:
        try:
            parts = urlsplit(url)
            port = parts.port
        except (TypeError, ValueError):
            raise ValueError("readyz URL is not allowlisted") from None

        if (
            parts.scheme.casefold() != "http"
            or parts.hostname is None
            or not _is_loopback_host(parts.hostname)
            or parts.username is not None
            or parts.password is not None
            or parts.path != "/readyz"
            or bool(parts.query)
            or bool(parts.fragment)
            or port is None
            or not 1 <= port <= 65535
        ):
            raise ValueError("readyz URL is not allowlisted")
