"""Per-worker Serena configuration surface (WO-P1-048).

Typed, validated settings edited through the Conductor UI, rendered into a
complete ``serena_config.yml`` for the worker's isolated ``SERENA_HOME`` and
applied on worker restart. Serena remains the config consumer; Conductor owns
generation. No live worker is mutated by this module.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

_WORKER_ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
_TOOL_NAME_RE = re.compile(r"^[a-z0-9_]+$")
_MODE_NAME_RE = re.compile(r"^[a-z0-9_-]+$")

_MIN_TOOL_TIMEOUT = 1
_MAX_TOOL_TIMEOUT = 86400


class LanguageBackend(str, Enum):
    LSP = "LSP"
    JETBRAINS = "JetBrains"


def _require_identifier_tuple(
    values: tuple[str, ...],
    field_name: str,
    pattern: re.Pattern[str],
) -> tuple[str, ...]:
    if not isinstance(values, tuple):
        raise ValueError(f"{field_name} must be a tuple of strings")
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str) or pattern.fullmatch(value) is None:
            raise ValueError(f"{field_name} contains an invalid name: {value!r}")
        if value in seen:
            raise ValueError(f"{field_name} contains duplicates: {value!r}")
        seen.add(value)
    return values


@dataclass(frozen=True, slots=True)
class WorkerSerenaSettings:
    worker_id: str
    language_backend: LanguageBackend = LanguageBackend.LSP
    excluded_tools: tuple[str, ...] = ()
    included_optional_tools: tuple[str, ...] = ()
    fixed_tools: tuple[str, ...] = ()
    base_modes: tuple[str, ...] = ()
    tool_timeout: int = 240

    def __post_init__(self) -> None:
        if (
            not isinstance(self.worker_id, str)
            or _WORKER_ID_RE.fullmatch(self.worker_id) is None
        ):
            raise ValueError("worker_id must match ^[a-z0-9][a-z0-9-]*$")
        if not isinstance(self.language_backend, LanguageBackend):
            raise ValueError("language_backend must be a LanguageBackend")
        _require_identifier_tuple(self.excluded_tools, "excluded_tools", _TOOL_NAME_RE)
        _require_identifier_tuple(
            self.included_optional_tools, "included_optional_tools", _TOOL_NAME_RE
        )
        _require_identifier_tuple(self.fixed_tools, "fixed_tools", _TOOL_NAME_RE)
        _require_identifier_tuple(self.base_modes, "base_modes", _MODE_NAME_RE)
        if self.fixed_tools and (self.excluded_tools or self.included_optional_tools):
            raise ValueError("FIXED_TOOLS_EXCLUSIVE: fixed_tools cannot be combined with excluded/included tool lists")
        if (
            not isinstance(self.tool_timeout, int)
            or isinstance(self.tool_timeout, bool)
            or not _MIN_TOOL_TIMEOUT <= self.tool_timeout <= _MAX_TOOL_TIMEOUT
        ):
            raise ValueError(
                f"tool_timeout must be between {_MIN_TOOL_TIMEOUT} and {_MAX_TOOL_TIMEOUT}"
            )

    def render_serena_config(self, *, project_path: str) -> str:
        if not isinstance(project_path, str) or not project_path.strip() or "\x00" in project_path:
            raise ValueError("project_path must be a non-blank string")

        def yaml_list(values: tuple[str, ...]) -> str:
            if not values:
                return " []"
            return "\n" + "\n".join(f"- {value}" for value in values)

        lines = [
            "# Generated by A-Conductor (WO-P1-048). Applied on worker restart.",
            f"language_backend: {self.language_backend.value}",
            "line_ending: native",
            "gui_log_window: false",
            "web_dashboard: false",
            "web_dashboard_open_on_launch: false",
            "web_dashboard_interface:",
            "web_dashboard_listen_address: 127.0.0.1",
            "web_dashboard_trusted_hosts:",
            "- 127.0.0.1",
            "- localhost",
            "log_level: 20",
            "trace_lsp_communication: false",
            "ls_specific_settings: {}",
            "ls_priorities:",
            "ignored_paths: []",
            "read_only_memory_patterns: []",
            "ignored_memory_patterns: []",
            f"tool_timeout: {self.tool_timeout}",
            f"excluded_tools:{yaml_list(self.excluded_tools)}",
            f"included_optional_tools:{yaml_list(self.included_optional_tools)}",
            f"fixed_tools:{yaml_list(self.fixed_tools)}",
            f"base_modes:{yaml_list(self.base_modes)}",
            "default_modes:",
            "default_max_tool_answer_chars: 150000",
            "token_count_estimator: CHAR_COUNT",
            "symbol_info_budget: 10",
            'project_serena_folder_location: "$projectDir/.serena"',
            "trusted_project_path_patterns: []",
            "projects:",
            f"- '{project_path.replace(chr(39), '')}'",
        ]
        return "\n".join(lines) + "\n"


class WorkerSettingsApplyError(RuntimeError):
    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


def apply_worker_serena_settings(
    settings: WorkerSerenaSettings,
    *,
    instances_root: Path | str,
    project_path: str,
    serena_home_subdir: str = "serena-home",
) -> Path:
    """Render and atomically write the worker's serena_config.yml.

    Writes are confined to ``<instances_root>/<worker_id>/<serena_home_subdir>``;
    any traversal outside the resolved root fails closed.
    """
    if not isinstance(settings, WorkerSerenaSettings):
        raise WorkerSettingsApplyError("SETTINGS_INVALID")
    if not isinstance(serena_home_subdir, str) or not re.fullmatch(
        r"[A-Za-z0-9_-]+", serena_home_subdir
    ):
        raise WorkerSettingsApplyError("SERENA_HOME_SUBDIR_INVALID")
    root = Path(instances_root).expanduser().resolve(strict=False)
    if not root.is_dir():
        raise WorkerSettingsApplyError("INSTANCES_ROOT_NOT_FOUND")
    target_dir = (root / settings.worker_id / serena_home_subdir).resolve(strict=False)
    if target_dir != root / settings.worker_id / serena_home_subdir or root not in target_dir.parents:
        raise WorkerSettingsApplyError("SETTINGS_TARGET_OUTSIDE_ROOT")
    target_dir.mkdir(parents=True, exist_ok=True)

    rendered = settings.render_serena_config(project_path=project_path)
    target = target_dir / "serena_config.yml"
    temp_path = target_dir / ".serena_config.yml.tmp"
    temp_path.write_text(rendered, encoding="utf-8", newline="\n")
    os.replace(temp_path, target)
    return target
